import React from 'react'
import Sathyatechcounter from './Sathyatechcounter'

function Containt(props) {
  return (
    <div>
      Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod quam nulla et voluptas. Repellat sit sapiente quaerat quo rem! Debitis unde quisquam facere, aspernatur earum officia veritatis, obcaecati aperiam natus tempore provident illum adipisci nesciunt? In numquam culpa quidem. Sint voluptatum possimus assumenda, deleniti fugiat eligendi facere illo suscipit nam fugit ipsa, eos quo perspiciatis nobis quos repudiandae quam quibusdam. Placeat quas fugiat sapiente quidem nihil eaque. Repellendus iusto, repudiandae modi debitis aspernatur quis quibusdam voluptas at, nobis dolorem labore earum sint quod, tenetur quia ex placeat minus. Quae alias, ut libero dignissimos quos deleniti iste sapiente! Magni, officia impedit.
      Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod quam nulla et voluptas. Repellat sit sapiente quaerat quo rem! Debitis unde quisquam facere, aspernatur earum officia veritatis, obcaecati aperiam natus tempore provident illum adipisci nesciunt? In numquam culpa quidem. Sint voluptatum possimus assumenda, deleniti fugiat eligendi facere illo suscipit nam fugit ipsa, eos quo perspiciatis nobis quos repudiandae quam quibusdam. Placeat quas fugiat sapiente quidem nihil eaque. Repellendus iusto, repudiandae modi debitis aspernatur quis quibusdam voluptas at, nobis dolorem labore earum sint quod, tenetur quia ex placeat minus. Quae alias, ut libero dignissimos quos deleniti iste sapiente! Magni, officia impe
      Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod quam nulla et voluptas. Repellat sit sapiente quaerat quo rem! Debitis unde quisquam facere, aspernatur earum officia veritatis, obcaecati aperiam natus tempore provident illum adipisci nesciunt? In numquam culpa quidem. Sint voluptatum possimus assumenda, deleniti fugiat eligendi facere illo suscipit nam fugit ipsa, eos quo perspiciatis nobis quos repudiandae quam quibusdam. Placeat quas fugiat sapiente quidem nihil eaque. Repellendus iusto, repudiandae modi debitis aspernatur quis quibusdam voluptas at, nobis dolorem labore earum sint quod, tenetur quia ex placeat minus. Quae alias, ut libero dignissimos quos deleniti iste sapiente! Magni, officia impe Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod quam nulla et voluptas. Repellat sit sapiente quaerat quo rem! Debitis unde quisquam facere, aspernatur earum officia veritatis, obcaecati aperiam natus tempore provident illum adipisci nesciunt? In numquam culpa quidem. Sint voluptatum possimus assumenda, deleniti fugiat eligendi facere illo suscipit nam fugit ipsa, eos quo perspiciatis nobis quos repudiandae quam quibusdam. Placeat quas fugiat sapiente quidem nihil eaque. Repellendus iusto, repudiandae modi debitis aspernatur quis quibusdam voluptas at, nobis dolorem labore earum sint quod, tenetur quia ex placeat minus. Quae alias, ut libero dignissimos quos deleniti iste sapiente! Magni, officia impe Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod quam nulla et voluptas. Repellat sit sapiente quaerat quo rem! Debitis unde quisquam facere, aspernatur earum officia veritatis, obcaecati aperiam natus tempore provident illum adipisci nesciunt? In numquam culpa quidem. Sint voluptatum possimus assumenda, deleniti fugiat eligendi facere illo suscipit nam fugit ipsa, eos quo perspiciatis nobis quos repudiandae quam quibusdam. Placeat quas fugiat sapiente quidem nihil eaque. Repellendus iusto, repudiandae modi debitis aspernatur quis quibusdam voluptas at, nobis dolorem labore earum sint quod, tenetur quia ex placeat minus. 
      <Sathyatechcounter countnum1={props.countnum} countnumset1={props.countnumset} student1={props.student} setstudent1={props.setstudent} studentplac1={props.studentplacement} setstudentplace1={props.setstudentplac}/>
    </div>
  )
}

export default Containt
